---
- hosts: mywebservers
  become: yes
  tasks:
   - name: i want to install java on ansible ubuntu nodes
     apt:
       name: "{{myjavapackinstallubuntu}}" 
       state: present
     when: ansible_os_family =="Debian"

   - name: i want to install java on ansible RedHat nodes
     yum:     
       name: "{{myjavapackinstallRedHat}}"
       state: present
     when: ansible_os_family =="RedHat"  